- name: Test EE with Azure collection on Controller 3
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Mostrar la ruta de Python (debería estar dentro del EE)
      ansible.builtin.command: which python3
      register: python_path

    - debug:
        var: python_path.stdout

    - name: Check system Python packages (should not have azure libs)
      ansible.builtin.command: pip3 list
      register: pip_list_output
      ignore_errors: yes

    - name: Show installed system packages
      ansible.builtin.debug:
        var: pip_list_output.stdout_lines

    - name: Try Azure module from EE (should work even if not installed on system)
      azure.azcollection.azure_rm_resourcegroup_info:
        auth_source: auto
      register: result
      ignore_errors: yes

    - name: Show result of Azure module call
      ansible.builtin.debug:
        var: result
