- name: Test EE with Azure collection on Controller 3
  hosts: all
  gather_facts: false

  tasks:
    - name: Check system Python packages (should not have azure libs)
      command: pip3 list
      register: pip_list_output
      ignore_errors: yes

    - name: Show installed system packages
      debug:
        var: pip_list_output.stdout_lines

    - name: Try Azure module from EE (should work even if not installed on system)
      azure.azcollection.azure_rm_resourcegroup_info:
        auth_source: auto
      register: result
      ignore_errors: yes

    - name: Show result of Azure module call
      debug:
        var: result
